config/routes.rb
Bookstore::Application.routes.draw do
  resources :lineitems

  resources :carts

  get "shop/index"

  resources :orders

  resources :accounts

  resources :users
  resources :sessions
  resources :books
  match '/sign_in',  :to => 'sessions#new'
  match '/sign_out', :to => 'sessions#destroy'
  match '/search', :to=> 'books#search'

  root :to => 'books#index'

end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base
  attr_accessible :book_id, :cart_id, :order_id, :quantity

  belongs_to :cart
  belongs_to :order
  belongs_to :book

end

app/controllers/lineitems_controller.rb
class LineitemsController < ApplicationController
  # GET /lineitems
  # GET /lineitems.json
  def index
    @lineitems = Lineitem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lineitems }
    end
  end

  # GET /lineitems/1
  # GET /lineitems/1.json
  def show
    @lineitem = Lineitem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lineitem }
    end
  end

  # GET /lineitems/new
  # GET /lineitems/new.json
  def new
    @lineitem = Lineitem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lineitem }
    end
  end

  # GET /lineitems/1/edit
  def edit
    @lineitem = Lineitem.find(params[:id])
  end

  # POST /lineitems
  # POST /lineitems.json
  def create
    @cart = current_cart
    book = Book.find(params[:book_id])
    @lineitem = @cart.add_book(book.id)

    respond_to do |format|
      if @lineitem.save
        format.html { redirect_to root_path, notice: 'Lineitem was successfully created.' }
        format.js
        format.json { render json: @lineitem, status: :created, location: @lineitem }
      else
        format.html { render action: "new" }
        format.json { render json: @lineitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lineitems/1
  # PUT /lineitems/1.json
  def update
    @lineitem = Lineitem.find(params[:id])

    respond_to do |format|
      if @lineitem.update_attributes(params[:lineitem])
        format.html { redirect_to @lineitem, notice: 'Lineitem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lineitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lineitems/1
  # DELETE /lineitems/1.json
  def destroy
    @lineitem = Lineitem.find(params[:id])
    @lineitem.destroy

    respond_to do |format|
      format.html { redirect_to lineitems_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/views/lineitems/_form.html.erb
<%= form_for(@lineitem) do |f| %>
  <% if @lineitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lineitem.errors.count, "error") %> prohibited this lineitem from being saved:</h2>

      <ul>
      <% @lineitem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :book_id %><br />
    <%= f.number_field :book_id %>
  </div>
  <div class="field">
    <%= f.label :order_id %><br />
    <%= f.number_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br />
    <%= f.number_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lineitems/create.js.erb
$('#cart').html("<%=j render @cart %>");

$('.item').css({'background-color':'#494E49'}).animate({'background-color':'white'}, 2000);

app/views/lineitems/edit.html.erb
<h1>Editing lineitem</h1>

<%= render 'form' %>

<%= link_to 'Show', @lineitem %> |
<%= link_to 'Back', lineitems_path %>

app/views/lineitems/index.html.erb
<h1>Listing lineitems</h1>

<table>
  <tr>
    <th>Book</th>
    <th>Order</th>
    <th>Quantity</th>
    <th>Cart</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lineitems.each do |lineitem| %>
  <tr>
    <td><%= lineitem.book_id %></td>
    <td><%= lineitem.order_id %></td>
    <td><%= lineitem.quantity %></td>
    <td><%= lineitem.cart_id %></td>
    <td><%= link_to 'Show', lineitem %></td>
    <td><%= link_to 'Edit', edit_lineitem_path(lineitem) %></td>
    <td><%= link_to 'Destroy', lineitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lineitem', new_lineitem_path %>

app/views/lineitems/new.html.erb
<h1>New lineitem</h1>

<%= render 'form' %>

<%= link_to 'Back', lineitems_path %>

app/views/lineitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Book:</b>
  <%= @lineitem.book_id %>
</p>

<p>
  <b>Order:</b>
  <%= @lineitem.order_id %>
</p>

<p>
  <b>Quantity:</b>
  <%= @lineitem.quantity %>
</p>

<p>
  <b>Cart:</b>
  <%= @lineitem.cart_id %>
</p>


<%= link_to 'Edit', edit_lineitem_path(@lineitem) %> |
<%= link_to 'Back', lineitems_path %>